### PR TITLE
gpu-compute,mem-ruby: Add RubyHitMiss flag for TCP and TCC cache

### PR DESCRIPTION
**Pull request by yuxiaojia**
Add hit and miss print for TCP and TCC cache with RubyHitMiss debug flag

Change-Id: I40ae3449020b917f39ac91d29fa4e1dd7c791e7b

### CODE REVIEW

**Review by powerjg — COMMENTED** [review]
I'll approve this if you will confirm the following:
- This has been compiled and tested with a GPU script (e.g., gpu_se.py or mi200.py)

**Review by mattsinc — COMMENTED** [review]
In terms of changes, it looks like this does what @abmerop asked for in the prior version we reverted.  However, as @powerjg said, since we cannot rely on CI to compile the GPU builds, yes we need to make sure things compile before we can check any GPU commits in moving forward (including this one).

**Comment by yuxiaojia** [comment]
> I'll approve this if you will confirm the following:
> 
> * This has been compiled and tested with a GPU script (e.g., gpu_se.py or mi200.py)

Hi Jason, thanks for your comment. I have fully tested with apu_se.py this time which works as expected.

**Comment by mattsinc** [comment]
> > I'll approve this if you will confirm the following:
> > 
> > * This has been compiled and tested with a GPU script (e.g., gpu_se.py or mi200.py)
> 
> Hi Jason, thanks for your comment. I have fully tested with apu_se.py this time which works as expected.

@yuxiaojia : given the problems last time, can you please also run with gpufs and make sure that works too?

**Comment by mattsinc** [comment]
> > > I'll approve this if you will confirm the following:
> > > 
> > > * This has been compiled and tested with a GPU script (e.g., gpu_se.py or mi200.py)
> > 
> > 
> > Hi Jason, thanks for your comment. I have fully tested with apu_se.py this time which works as expected.
> 
> @yuxiaojia : given the problems last time, can you please also run with gpufs and make sure that works too?

@yuxiaojia just checking on this

**Comment by yuxiaojia** [comment]
> > > > I'll approve this if you will confirm the following:
> > > > 
> > > > * This has been compiled and tested with a GPU script (e.g., gpu_se.py or mi200.py)
> > > 
> > > 
> > > Hi Jason, thanks for your comment. I have fully tested with apu_se.py this time which works as expected.
> > 
> > 
> > @yuxiaojia : given the problems last time, can you please also run with gpufs and make sure that works too?
> 
> @yuxiaojia just checking on this

Sorry for the late response, seems like gpufs could run to complete on my end.

**Review by mattsinc — APPROVED** [review]

**Comment by mattsinc** [comment]
thanks @yuxiaojia !

**Pull request merged**
