### PR TITLE
gpu-compute, tests: Fix GPU_X86 compilation, add compiler tests

### PR DESCRIPTION
**Pull request by BobbyRBruce**
Fixes the compilation for "VEGA_X86" and "GPU_X86" as well adds tests to the compiler tests so these compilation issues are captured earlier.

### CODE REVIEW

**Review by powerjg — APPROVED** [review]
lgtm

**Comment by mattsinc** [comment]
How would I approve this?  I don't see a button for me ...

**Comment by powerjg** [comment]
Hi Matt,

I am not certain that maintainers had the right permissions. I tried something else on my end. Can you try again?

Things are quite different from gerrit. Have you read github's documentation? https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request

Also, the tests are failing for this so there's no way to merge until the tests pass.

**Review by mattsinc — APPROVED** [review]
Test

**Comment by mattsinc** [comment]
> Hi Matt,
> 
> I am not certain that maintainers had the right permissions. I tried something else on my end. Can you try again?
> 
> Things are quite different from gerrit. Have you read github's documentation? https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request
> 
> Also, the tests are failing for this so there's no way to merge until the tests pass.

Looks like the problem was I hadn't accepted @mkjost0 's invite yet.  After accepting that, things seem to be working now.

**Pull request merged**
