### PR TITLE
[DO NOT MERGE][Test-only] test kconfig weekly tests and gpu tests

### PR DESCRIPTION
**Pull request by rogerchang23424**

### CODE REVIEW

**Comment by powerjg** [comment]
I'm not sure this is the best way to test things... we don't have *free* compute resources. By running the weekly tests like this you're taking valuable CI testing resources from others in the community.

In this case, we don't need to ensure that the tests completely pass, only that the *build* works. Would it be possible to simply manually inspect the files instead of using 3-5 days of testing resources?

**Comment by powerjg** [comment]
Apologies. I need to convert this to a draft so it stops taking all of our CI testing resources.

**Comment by rogerchang23424** [comment]
OK, I have removed the very-long tests in the weekly and gpu tests and only leave the tests need to build

**Comment by rogerchang23424** [comment]
The PR is just test if the weekly test will break after kconfig changes. Close the PR we don't need to run test anymore.

**Pull request closed without merging**
