### PR TITLE
misc: Merge develop .github into stable

### PR DESCRIPTION
**Pull request by BobbyRBruce**

### CODE REVIEW

**Comment by giactra** [comment]
Hi Bobby, can we add the following PR as well?

https://github.com/gem5/gem5/pull/114

It is rather important it makes it to the minor release

**Comment by BobbyRBruce** [comment]
> Hi Bobby, can we add the following PR as well?
> 
> #114
> 
> It is rather important it makes it to the minor release

Yip, I'll make sure it gets in!

**Comment by giactra** [comment]
Many thanks!

**Comment by powerjg** [comment]
Requires #105

**Comment by BobbyRBruce** [comment]
> Requires #105

This has been incorporated. I'll merge this to stable after the tests pass.

**Comment by BobbyRBruce** [comment]
Updated this to incorporate https://github.com/gem5/gem5/pull/136. Rerunning tests.

**Review by mkjost0 — APPROVED** [review]

**Pull request merged**
