### PR TITLE
gpu-compute,mem-ruby: Revert "Add RubyHitMiss flag for TCP and TCC cache"

### PR DESCRIPTION
**Pull request by BobbyRBruce**
Reverts gem5/gem5#1226

### CODE REVIEW

**Review by mattsinc — APPROVED** [review]
I am a little confused why the compilation that happens with each commit didn't catch this, but for now approving until @yuxiaojia can fix locally.

**Comment by abmerop** [comment]
> I am a little confused why the compilation that happens with each commit didn't catch this, but for now approving until @yuxiaojia can fix locally.

The short answer is build/ALL/gem5.opt built by the CI test doesn't build the GPU files (BUILD_GPU=False).

**Review by abmerop — APPROVED** [review]

**Comment by mattsinc** [comment]
> > I am a little confused why the compilation that happens with each commit didn't catch this, but for now approving until @yuxiaojia can fix locally.
> 
> The short answer is build/ALL/gem5.opt built by the CI test doesn't build the GPU files (BUILD_GPU=False).

That's probably not good if GPU builds are not being included in CI per-checkin tests?  I'm sure there is a good reason I'm just forgetting though.

**Comment by BobbyRBruce** [comment]
> > > I am a little confused why the compilation that happens with each commit didn't catch this, but for now approving until @yuxiaojia can fix locally.
> > 
> > 
> > The short answer is build/ALL/gem5.opt built by the CI test doesn't build the GPU files (BUILD_GPU=False).
> 
> That's probably not good if GPU builds are not being included in CI per-checkin tests? I'm sure there is a good reason I'm just forgetting though.

We just can't afford to do a lot of compilations for the CI tests. We compile ALL and run tests which use ALL and save varying different compilations for Daily or Weekly tests.

**Comment by abmerop** [comment]
> > > > I am a little confused why the compilation that happens with each commit didn't catch this, but for now approving until @yuxiaojia can fix locally.
> > > 
> > > 
> > > The short answer is build/ALL/gem5.opt built by the CI test doesn't build the GPU files (BUILD_GPU=False).
> > 
> > 
> > That's probably not good if GPU builds are not being included in CI per-checkin tests? I'm sure there is a good reason I'm just forgetting though.
> 
> We just can't afford to do a lot of compilations for the CI tests. We compile ALL and run tests which use ALL and save varying different compilations for Daily or Weekly tests.

I did a quick test adding BUILD_GPU=True to build_opts/ALL and it *does* compile.  I don't know how much more time that adds though.  Plus you cannot run anything with it anyway.  That would require building all ruby protocols too.

**Pull request merged**
