### PR TITLE
tests: fix lulesh

### PR DESCRIPTION
**Pull request by Harshil2107**
- fixed the broken command that was causing lulesh to fail the run
Change-Id: I4e8a310f153d86deb8829f41b5ddd0c317df23cb

### CODE REVIEW

**Review by mattsinc — COMMENTED** [review]
I see this is a draft, but the change looks correct to me.  Let me know when you want it approved.

**Comment by Harshil2107** [comment]
Sorry, I didn't mean to set it as a draft.

**Review by mattsinc — APPROVED** [review]

**Review by BobbyRBruce — APPROVED** [review]

**Comment by Harshil2107** [comment]
Hi @mattsinc,
The lulesh tests are still failing with the error `fatal: lulesh not found in ['lulesh']`. I was able to fix that by running the following command `build/GCN3_X86/gem5.opt configs/example/apu_se.py -n3 --mem-size=8GB --reg-alloc-policy=dynamic -c  lulesh --options="0.01 2"`. Now lulesh seems to fail with a memory violation.

I ran lulesh in the docker `containerghcr.io/gem5/gcn-gpu:latest`. These are the steps I followed:
```
> docker pull ghcr.io/gem5/gcn-gpu:latest
> docker run -i -t ghcr.io/gem5/gcn-gpu:latest /bin/bash
```
In the terminal for the docker container, I ran the following commads:
```
> git clone https://github.com/gem5/gem5.git
> cd gem5
> git fetch
> git checkout develop
> scons build/GCN3_X86/gem5.opt -j $(nproc) --ignore-style
> build/GCN3_X86/gem5.opt util/obtain-resource.py lulesh -p lulesh
> build/GCN3_X86/gem5.opt configs/example/apu_se.py -n3 --mem-size=8GB --reg-alloc-policy=dynamic -c  lulesh --options="0.01 2"
```

These are the last few lines of the terminal output:

```
src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
src/arch/generic/debugfaults.hh:145: warn: MOVNTDQ: Ignoring non-temporal hint, modeling as cacheable!
src/gpu-compute/gpu_command_processor.cc:528: warn: Ignoring vendor packet
src/gpu-compute/gpu_dyn_inst.cc:787: fatal: flat access at addr 0x2000000000000800 has a memory violation
Memory Usage: 20388056 KBytes

```

**Comment by mattsinc** [comment]
> Hi @mattsinc, The lulesh tests are still failing with the error `fatal: lulesh not found in ['lulesh']`. I was able to fix that by running the following command `build/GCN3_X86/gem5.opt configs/example/apu_se.py -n3 --mem-size=8GB --reg-alloc-policy=dynamic -c lulesh --options="0.01 2"`. Now lulesh seems to fail with a memory violation.
> 
> I ran lulesh in the docker `containerghcr.io/gem5/gcn-gpu:latest`. These are the steps I followed:
> 
> ```
> > docker pull ghcr.io/gem5/gcn-gpu:latest
> > docker run -i -t ghcr.io/gem5/gcn-gpu:latest /bin/bash
> ```
> 
> In the terminal for the docker container, I ran the following commads:
> 
> ```
> > git clone https://github.com/gem5/gem5.git
> > cd gem5
> > git fetch
> > git checkout develop
> > scons build/GCN3_X86/gem5.opt -j $(nproc) --ignore-style
> > build/GCN3_X86/gem5.opt util/obtain-resource.py lulesh -p lulesh
> > build/GCN3_X86/gem5.opt configs/example/apu_se.py -n3 --mem-size=8GB --reg-alloc-policy=dynamic -c  lulesh --options="0.01 2"
> ```
> 
> These are the last few lines of the terminal output:
> 
> ```
> src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
> src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
> src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
> src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
> src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
> src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
> src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
> src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
> src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
> src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
> src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
> src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
> src/arch/generic/debugfaults.hh:145: warn: MOVNTDQ: Ignoring non-temporal hint, modeling as cacheable!
> src/gpu-compute/gpu_command_processor.cc:528: warn: Ignoring vendor packet
> src/gpu-compute/gpu_dyn_inst.cc:787: fatal: flat access at addr 0x2000000000000800 has a memory violation
> Memory Usage: 20388056 KBytes
> ```

I am not sure I understand what change you had to make for the binary, but sounds like you fixed it so great.

The second error you are facing is the same one we discussed here: https://github.com/gem5/gem5/pull/540.  I @'d you in the comment where we discussed it there, but ultimately if you are using GCN3_X86 I believe you need to specify --gfx-version=gfx801 on the command line.  If you are using VEGA_X86 then you need --dgpu --gfx-version=gfx900 on the command line.  I was only testing VEGA_X86 not GCN3_X86 when I encountered this error, so I'm only mostly confident in the GCN3_X86 fix but I know it works for the VEGA_X86 one.

**Comment by Harshil2107** [comment]
> > Hi @mattsinc, The lulesh tests are still failing with the error `fatal: lulesh not found in ['lulesh']`. I was able to fix that by running the following command `build/GCN3_X86/gem5.opt configs/example/apu_se.py -n3 --mem-size=8GB --reg-alloc-policy=dynamic -c lulesh --options="0.01 2"`. Now lulesh seems to fail with a memory violation.
> > I ran lulesh in the docker `containerghcr.io/gem5/gcn-gpu:latest`. These are the steps I followed:
> > ```
> > > docker pull ghcr.io/gem5/gcn-gpu:latest
> > > docker run -i -t ghcr.io/gem5/gcn-gpu:latest /bin/bash
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In the terminal for the docker container, I ran the following commads:
> > ```
> > > git clone https://github.com/gem5/gem5.git
> > > cd gem5
> > > git fetch
> > > git checkout develop
> > > scons build/GCN3_X86/gem5.opt -j $(nproc) --ignore-style
> > > build/GCN3_X86/gem5.opt util/obtain-resource.py lulesh -p lulesh
> > > build/GCN3_X86/gem5.opt configs/example/apu_se.py -n3 --mem-size=8GB --reg-alloc-policy=dynamic -c  lulesh --options="0.01 2"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > These are the last few lines of the terminal output:
> > ```
> > src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
> > src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
> > src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
> > src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
> > src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
> > src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
> > src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
> > src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
> > src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
> > src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
> > src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
> > src/sim/syscall_emul.cc:74: warn: ignoring syscall mprotect(...)
> > src/arch/generic/debugfaults.hh:145: warn: MOVNTDQ: Ignoring non-temporal hint, modeling as cacheable!
> > src/gpu-compute/gpu_command_processor.cc:528: warn: Ignoring vendor packet
> > src/gpu-compute/gpu_dyn_inst.cc:787: fatal: flat access at addr 0x2000000000000800 has a memory violation
> > Memory Usage: 20388056 KBytes
> > ```
> 
> I am not sure I understand what change you had to make for the binary, but sounds like you fixed it so great.
> 
> The second error you are facing is the same one we discussed here: #540. I @'d you in the comment where we discussed it there, but ultimately if you are using GCN3_X86 I believe you need to specify --gfx-version=gfx801 on the command line. If you are using VEGA_X86 then you need --dgpu --gfx-version=gfx900 on the command line. I was only testing VEGA_X86 not GCN3_X86 when I encountered this error, so I'm only mostly confident in the GCN3_X86 fix but I know it works for the VEGA_X86 one.

Building and running lulesh with GCN3_X86 still causes the issue but with VEGA_X86 I think it completes the run. This is the output I get with the vega:
```
src/gpu-compute/gpu_compute_driver.cc:887: warn: unimplemented ioctl: AMDKFD_IOC_MAP_MEMORY_TO_GPU
src/sim/syscall_emul.cc:74: warn: ignoring syscall mbind(...)
src/sim/syscall_emul.cc:74: warn: ignoring syscall get_mempolicy(...)
src/sim/syscall_emul.cc:74: warn: ignoring syscall madvise(...)
src/gpu-compute/gpu_compute_driver.cc:887: warn: unimplemented ioctl: AMDKFD_IOC_MAP_MEMORY_TO_GPU
src/sim/syscall_emul.cc:74: warn: ignoring syscall mbind(...)
time = 2.200000e-07, dt=1.200000e-07
iterations: 2
src/sim/syscall_emul.cc:74: warn: ignoring syscall mbind(...)
Ticks: 706876289500
Exiting because  exiting with last active thread context
```

Should I switch the workflow file to use VEGA_X86?

**Comment by abmerop** [comment]
I would recommend using VEGA. It is essentially a superset ISA of GCN3 meaning all of the features GCN3 has are in Vega and more.  We started discussing removing GCN3 in #306. 

As a side not, that memory violation address looks very much like an incorrectly generated scratch/private memory address. Although I do remember working with Matt and some students to fix that, maybe even more than once...

**Comment by mattsinc** [comment]
> I would recommend using VEGA. It is essentially a superset ISA of GCN3 meaning all of the features GCN3 has are in Vega and more. We started discussing removing GCN3 in #306.
> 
> As a side not, that memory violation address looks very much like an incorrectly generated scratch/private memory address. Although I do remember working with Matt and some students to fix that, maybe even more than once...

Perhaps we forgot to apply a patch to GCN3?  In any event, yes we are moving towards VEGA so I think it's fine to do so here.  Although I'm not sure if that causes knock on issues for the tester having 2 separate GPU ISAs being tested?

**Comment by Harshil2107** [comment]
I pushed a patch to switch lulesh to vega_x86, #620.

**Pull request merged**
