### PR TITLE
Update & fix bug in m5stats2streamline.py

### LINKED ISSUE #145: gem5 to Streamline apc file has error
**Describe the bug**
util/streamline/m5stats2streamline.py script produced .apc file is invalid
--> in newer DS-5 streamline (29rel1), ultimate edition --> invalid apc format
--> in older DS-5 streamline (24rel1), ultimate edition --> error is,
Error detected in the binary data with respect to end-of-line markers. Check the settings on any FTP tools used and ensure any ASCII end-of-line conversions are disabled.
  java.io.IOException: Error detected in the binary data with respect to end-of-line markers. Check the settings on any FTP tools used and ensure any ASCII end-of-line conversions are disabled.
  	at com.arm.streamline.analysis.gator.GatorProtocolV17.processSummary(GatorProtocolV17.java:107)
  	at com.arm.streamline.analysis.gator.GatorProtocolV17.process(GatorProtocolV17.java:62)
  	at com.arm.streamline.analysis.gator.GatorDatabase.processOnce(GatorDatabase.java:127)
  	at com.arm.streamline.analysis.gator.GatorDatabase.processOnce(GatorDatabase.java:137)
  	at com.arm.streamline.analysis.gator.GatorDatabase.process(GatorDatabase.java:145)
  	at com.arm.streamline.analysis.AnalysisBase.run(AnalysisBase.java:59)
  	at java.lang.Thread.run(Thread.java:745)

**Affects version**
v22.1, v23.0

**gem5 Modifications**
The modification done mainly in the util/streamline/m5stats2streamline.py . 
1) in the function,

```

def string_to_int(string): #added function
  try:
    return int(string)
  except ValueError:
    return None

############################################################
# Write binary
############################################################
def writeBinary(outfile, binary_list):
    for i in binary_list: #added line
        if isinstance(i,str): #added line
            i_temp = string_to_int(i) #added line
            if (i_temp == None): #added line
                i = i #added line
            else: #added line
                i=i_temp #added line
        if isinstance(i,int): #added line
            i = chr(i) #added line
        byteVal = bytes(i, "utf-8") #added line
        #outfile.write(f"{i:c}") # original line
        outfile.write(byteVal) #added line
```

I see that in binary_list provided to writeBinary sometimes has combination of int and strings! . so just outfile.write(f"{i:c}") gives type error that byte like object need and not str.

2) packed32(x) function, where x has to be int and sometimes its  not int and its float!

```
def packed32(x):
    ret = []
    more = True
    while more:
        x =int(x) #added line
        b = x & 0x7F
        x = x >> 7
        if ((x == 0) and ((b & 0x40) == 0)) or (
            (x == -1) and ((b & 0x40) != 0)
        ):
            more = False
        else:
            b = b | 0x80
        ret.append(b)
    return ret


```

**Expected behavior**
Expected behavior is to see the waveform in arm DS-5 streamline for gem5 FS of arm-linux. I have the license for older streamline version that could be compatible with gem5 conversion script.

**Host Operating System**
Ubuntu 18.04

**Host ISA**
x864

**Reproduce**
I have enabled context switch dump. I attached the files,
```
python m5stats2streamline.py ./stat_config.ini ./streamline ./streamline.apc
zip -r ./streamline.apc.zip ./streamline.apc (then import the apc.zip file in DS-5 streamline)

```

### PR DESCRIPTION
**Pull request by atrah22**
There is conversion error in ./util/streamline/m5stats2streamline.py script to convert gem5 stats.txt,sys, system.tasks.txt to the apc folder required by DS-5 streamline. The fix to the bug can convert to apc folder without error. The zipped apc folder can then be imported in older DS-5 v5.24 for visualization (didn't work with DS-5 v5.29).

Changes:
1) writeBinary function's input "binarylist" can have either string or integers and it needs to be properly converted to bytes 
2) packed32(x) function's input "x" can be either integer or float. Incase of float it needs to be converted to integer.

The bug was reported and solved primarily in the issue https://github.com/gem5/gem5/issues/145

### CODE REVIEW

**Comment by mkjost0** [comment]
Hi, this test is failing the Change-ID check and pre-commit check.

In order for the Change-ID test to pass, you must ensure you commit message has a Change-ID at the bottom. To amend your commit, run the following commands:

`f=`git rev-parse --git-dir`/hooks/commit-msg ; mkdir -p $(dirname $f) ; curl -Lo $f https://gerrit-review.googlesource.com/tools/hooks/commit-msg ; chmod +x $f` then run `git commit --amend --no-edit`
To learn more about Change-Ids, go here: https://www.gem5.org/documentation/general_docs/common-errors/#change-id

In order for the pre-commit test to pass, please ensure all code committed follows the style for gem5. You can run util/pre-commit-install.sh to install pre-commit, and run pre-commit run <hook_id> on your commit to automatically reformat your files. More information about pre-commit can be found here: https://www.gem5.org/documentation/general_docs/common-errors/#precommit

In addition, the commit message does not adhere to our current standard, and should include a tag within the header to categorize your changes. You can read more about how to format your commit message in the committing section here (https://www.gem5.org/contributing), and see a list of accepted tags here (https://github.com/gem5/gem5/blob/stable/MAINTAINERS.yaml)

Thanks!

**Comment by BobbyRBruce** [comment]
The pre-commit checks failed. You can fix this locally using:

```sh
./util/pre-commit-install.sh # Ensure the hooks are installed
pre-commit run --files <files modified in this patch>
git add <files fixed by pre-commit>
git commit -m "misc: Fix pre-commit formatting issues"
```

This should also add the change ID to the commit.

**Comment by BobbyRBruce** [comment]
Also, if you could update the commit and PR header/title to have the `util` tag: "util: Update & fix bug in m5stats2streamline.py".

**Comment by BobbyRBruce** [comment]
@atrah22 : Is this PR officially closed or are you still making more changes to it and wish to incorporate it at some point. "Closed" to me indicates abandonment. If you still want to contribute this at somepoint can I convert this as a "Draft" PR for you instead?

**Comment by BobbyRBruce** [comment]
> @atrah22 : Is this PR officially closed or are you still making more changes to it and wish to incorporate it at some point. "Closed" to me indicates abandonment. If you still want to contribute this at somepoint can I convert this as a "Draft" PR for you instead?

Never mind, I see this has been reopened, here: https://github.com/gem5/gem5/pull/211

**Pull request closed without merging**
