### PR TITLE
arch-riscv: Implemented zicbom/zicboz extensions for RISC V

### PR DESCRIPTION
**Pull request by rogerchang23424**
Change-Id: I79d0e6059a2dbb5a0057c4f7489b999f9e803684

### CODE REVIEW

**Comment by rogerchang23424** [comment]
This change is from: https://gem5-review.googlesource.com/c/public/gem5/+/71958

**Review by powerjg — COMMENTED** [review]
This change is OK. I wonder if we should add some warnings because I don't think that most of the cache models (Ruby or classic) support the INVALIDATE, CLEAN, or CACHE_BLOCK_ZERO flags.

Thoughts?

**Comment by rogerchang23424** [comment]
Pending until the RVV chain(PR#83) merged

**Comment by powerjg** [comment]
> I wonder if we should add some warnings because I don't think that most of the cache models (Ruby or classic) support the INVALIDATE, CLEAN, or CACHE_BLOCK_ZERO flags.

Any thoughts on this?

**Comment by powerjg** [comment]
The RVV chain (#83) has been merged. Can you respond to my question above before we merge this?

**Comment by rogerchang23424** [comment]
> This change is OK. I wonder if we should add some warnings because I don't think that most of the cache models (Ruby or classic) support the INVALIDATE, CLEAN, or CACHE_BLOCK_ZERO flags.
> 
> Thoughts?

Hi,

The must of flags are defined in `mem/packets.hh` and CMOs are implemented in separate CPU models. Following are details about CMOs:

For the cache operation define with memory flags:
https://github.com/gem5/gem5/blob/stable/src/mem/request.hh#L1111

The Memcmd will update according to the memory flags:
https://github.com/gem5/gem5/blob/stable/src/mem/packet.hh#L993

For CACHE_BLOCK_ZERO
https://github.com/gem5/gem5/blob/stable/src/mem/request.hh#L260

I think it should warn inside the model if the model is not implemented for the specify MemCmd

**Comment by powerjg** [comment]
> I think it should warn inside the model if the model is not implemented for the specify MemCmd

Sounds good. I don't think that we do a good job of this, but you're right :)

**Review by powerjg — APPROVED** [review]

**Pull request merged**
