### PR TITLE
util: Bump gpu-fs docker to ROCm 6.1

### PR DESCRIPTION
**Pull request by abmerop**
This version matches the disk image on gem5-resources.

Change-Id: I69a45ef290f0fdf2167ead4d67d4d789d30e0e91

### CODE REVIEW

**Review by mattsinc — DISMISSED** [review]
From my perspective this is good, but @BobbyRBruce should probably chime in too

**Review by mattsinc — APPROVED** [review]
From my perspective this is good, but @BobbyRBruce should probably chime in too

**Comment by abmerop** [comment]
Updated README

**Comment by abmerop** [comment]
I don't think Bobby needs to review, but I think he updates the ghcr images which should be done for the release

**Comment by BobbyRBruce** [comment]
Sorry for the delay on this, but this image on our docker registry has been updated to incorporate this change as of this morning.

**Pull request merged**
