### PR TITLE
cpu-o3: add PerThreadUnifiedThreadMap to O3 CPU

### PR DESCRIPTION
**Pull request by Arnab035**
Github issue: https://github.com/gem5/gem5/issues/373

Change-Id: I1c8aba9bc5ea4e45faa6c174780904b8bd618604

### CODE REVIEW

**Review by BobbyRBruce — APPROVED** [review]

**Comment by BobbyRBruce** [comment]
@powerjg : Can you see if this looks right to you?

**Review by powerjg — CHANGES_REQUESTED** [review]
Before this is merged, we should answer the question below.

How does this relate to #828?

**Comment by Arnab035** [comment]
Hello @powerjg , sorry, I could not quite follow. Do I need to make additional changes in the PR?

**Comment by powerjg** [comment]
Can you explain how this relates to the PR linked above? 

I want to make sure this isn't two implementations solving the same problem.

**Comment by Arnab035** [comment]
Sure, I can! This PR is unrelated to the PR linked above.  

It seems the linked PR above is solving the issue when there are not enough physical registers to map to architectural registers during renaming in SMT. This PR adds a new datatype `PerThreadUnifiedRenameMap` to `O3:UnifiedRenameMap` which converts a C-style array to an std::array.  Additionally, I do not see any code conflicts between both the PRs.

**Review by powerjg — APPROVED** [review]

**Pull request merged**
