### PR TITLE
Fix Intel MCG_CAP MSR update on switch

### PR DESCRIPTION
**Pull request by Foxy-Boxes**
Reason: https://www.intel.com/content/dam/develop/external/us/en/documents/335592-sdm-vol-4.pdf 2-30.

### CODE REVIEW

**Comment by BobbyRBruce** [comment]
Thanks for the contribution. There's a few things that need fixed before we can merge this. 

1. Your commit is going to fail our tests as the commit message it doesn't conform to our guidelines. We're lacking tags and a Change-ID, and the header is >62 characters long. You can see read more about this in our contributing guidelines here: https://github.com/gem5/gem5/blob/stable/CONTRIBUTING.md.

The easiest to fix all these problems would be with the following:

```sh
# Install our pre-commit hook with our install script.
./util/pre-commit-install.sh

# Run the hook on your commit and change the message.
git commit --amend
```

In your editor interface, change the commit message to read

```
arch-x86: Fix Intel MCG_CAP MSR update on switch

reason: https://www.intel.com/content/dam/develop/external/us/en/documents/335592-sdm-vol-4.pdf (2-30)
```

Save and close the editor. The Change-Id will be automatically added by the git hook. You can verify this with `git log`.

You can then force push the change with:

```sh
git push -f origin gem5
```

 
2. You put this change on top of the `stable` branch. We make change on top of the `develop` branch. To fix this I'd recommend the following:

```sh
# Via `git log`, make not of the commit's SHA.
# Here I'll use '{SHA}' as a placeholder.

# Go to the develop branch of your git repository.
git switch develop

# Add the mainline gem5 repo as a remote repo and fetch it.
git remote add upstream https://github.com/gem5/gem5.git
git fetch upstream 

# Merge the upstream develop into your local develop branch.
git merge upstream/develop

# Create a new branch, from develop, for this change.
git switch -c pr-957-update

# Cherry Pick your change on top of this new branch.
git cherry-pick <SHA>

# Do a force push to this branch (i.e. https://github.com/Gem5Fork/gem5-fixintelmc/tree/stable).
git push -f origin stable
```

**Comment by Foxy-Boxes** [comment]
I have identified __mcheck_cpu_cap_init writes a kernel variable so that the capacity check is actually done with the initial value of the msr: MCG_CAP thus we need to change the value before  kvm starts, in short this is not ready yet.

**Review by BobbyRBruce — APPROVED** [review]

**Comment by ivanaamit** [comment]
Hi @Foxy-Boxes, what is the status of this PR? Thanks.

**Review by BobbyRBruce — APPROVED** [review]

**Comment by BobbyRBruce** [comment]
Closed and replaced with #1423. For some reason GitHub Actions does not like this PR so I just moved the change to a new one.

**Pull request closed without merging**
