### PR TITLE
cpu-kvm: properly set x86 xsave header on gem5->KVM transition

### LINKED ISSUE #296: X86KvmCPU incorrectly sets xsave struct before transitioning back to KVM
**Describe the bug**
The X86KvmCPU does not properly populate the KVM xsave region (in `struct kvm_xsave` in [X86KvmCPU::updateKvmStateFPUXSave()](https://github.com/gem5/gem5/blob/ebde1133c0057ca12cb6d58695df64071e4e4915/src/arch/x86/kvm/x86_cpu.cc#L906)
Specifically, it incorrectly memset's _all_ of the xsave region to zero, which notably zeroes out the bits in the xsave header (Vol. 1, Section 13.4.2 of Intel's Software Development Manual) that indicate the presence of x87 FPU (byte 0, bit 0 of the header) and SSE (byte 0, bit 1) state. This appears to cause the subsequent KVM API call `ioctl(KVM_SET_XSAVE, &kxsave)` ([here](https://github.com/gem5/gem5/blob/ebde1133c0057ca12cb6d58695df64071e4e4915/src/arch/x86/kvm/x86_cpu.cc#L925)) to apparently zero out all FPU and SSE state, causing seemingly random crashes or incorrect results in the application.

The following programs demonstrate this bug when running under syscall emulation mode:
`xmm.c`
```c
#include <sys/mman.h>
#include <stdio.h>

int main() {
  // Map new page into memory -- the first access to this page will trigger a page fault (transparent to user process).                                                                                                                                                         
  char *map = (char *) mmap(NULL, 0x1000, PROT_READ | PROT_WRITE, MAP_ANON | MAP_PRIVATE, -1, 0);
  if (map == MAP_FAILED) {
    perror("mmap");
    return 1;
  }

  asm volatile ("movq xmm0, %1\n" // temporarily move `map' into xmm0                                                                                                                                                                                                           
                "mov rax, [%1]\n" // read triggers page fault; gem5 XSAVE bug zeroes xmm0                                                                                                                                                                                       
                "movq %0, xmm0\n" // output variable `map' is assigned zero, not input value                                                                                                                                                                                    
                : "=r"(map)
                : "r"(map)
                : "rax"
                );
  *map = 0; // should execute normally, but triggers segfault in gem5, since map == 0                                                                                                                                                                                           
}
```

memset failure (how I initially found this bug)
`memset.c`
```c
#include <sys/mman.h>
#include <stdio.h>
#include <string.h>

int main() {
  // Map new page into memory -- the first access to this page will trigger a page fault (transparent to user process).                                                                                                                                                                                       
  const size_t size = 0x1000;
  char *map = mmap(NULL, size, PROT_READ | PROT_WRITE, MAP_ANON | MAP_PRIVATE, -1, 0);
  if (map == MAP_FAILED) {
    perror("mmap");
    return 1;
  }

  char fill = 0xab;
  /* Triggers a page fault on first write. gem5 XSAVE bug zeroes out the XMM register holding 0xABABABAB....                                                                                                                                                                    
   * in an optimized SSE memset implementation, causing memset to fill memory with 0x00 instead of 0xAB.                                                                                                                                                                        
   */
  memset(map, fill, size);

  /* Check whether memset succeeded. Under correct program/simulator behavior, this for-loop should print                                                                                                                                                                       
   * nothing.                                                                                                                                                                                                                                                                   
   */
  for (size_t i = 0; i < size; ++i) {
    if (map[i] != fill) {
      fprintf(stderr, "memset failed at address %p: %02hhx != %02hhx\n",
              &map[i], map[i], fill);
      return 1;
    }
  }
}
```

**Affects version**
develop @ ebde113

**gem5 Modifications**
None

**To Reproduce**
1. Compile the programs xmm.c and memcpy.c with: `cc -static -o xmm xmm.c -masm=intel` and `cc -static -o memset memset.c`.
2. Compile gem5 with: `scons build/X86/gem5.opt`
3. Execute the program `xmm` using the KVM CPU with: `./build/X86/gem5.opt configs/deprecated/example/se.py --cpu-type=X86KvmCPU --cmd=./xmm`
4. Execute the program `memset` using the KVM CPU with: `./build/X86/gem5.opt configs/deprecated/example/se.py --cpu-type=X86KvmCPU --cmd=./memset`

**Terminal Output**
The expected output of `./xmm` and `./memset` is nothing, i.e., they shouldn't print anything and exit cleanly (with exit code 0).

Actual output of `xmm` when run with X86KvmCPU -- it crashes:
```
...
src/arch/x86/linux/se_workload.cc:166: panic: Page fault at addr 0
        Interrupt handler stack:
        ss: 0x1b
        rsp: 0x7fffffffec80
        rflags: 0x10013
        cs: 0x23
        rip: 0x4017b0
        err_code: 0x6
Memory Usage: 639884 KBytes
Program aborted at tick 1359261000
--- BEGIN LIBC BACKTRACE ---
./build/X86/gem5.opt(_ZN4gem515print_backtraceEv+0x30)[0x55e6b2bf9680]
./build/X86/gem5.opt(_ZN4gem512abortHandlerEi+0x4c)[0x55e6b2c1dc0c]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7fc8b3977520]
/lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c)[0x7fc8b39cba7c]
/lib/x86_64-linux-gnu/libc.so.6(raise+0x16)[0x7fc8b3977476]
/lib/x86_64-linux-gnu/libc.so.6(abort+0xd3)[0x7fc8b395d7f3]
./build/X86/gem5.opt(+0xa25235)[0x55e6b20d1235]
./build/X86/gem5.opt(_ZN4gem56X86ISA8EmuLinux9pageFaultEPNS_13ThreadContextE+0x18a)[0x55e6b36d937a]
./build/X86/gem5.opt(_ZN4gem513invokeSimcallINS_16X86PseudoInstABIEJEEEvPNS_13ThreadContextEPFvS3_DpT0_E+0xc2)[0x55e6b3225482]
./build/X86/gem5.opt(+0x1b752d7)[0x55e6b32212d7]
./build/X86/gem5.opt(+0x1b753e1)[0x55e6b32213e1]
./build/X86/gem5.opt(_ZN4gem510BaseKvmCPU12doMMIOAccessEmPvib+0x4e4)[0x55e6b2f51c84]
./build/X86/gem5.opt(_ZN4gem510BaseKvmCPU13handleKvmExitEv+0x182)[0x55e6b2f521f2]
./build/X86/gem5.opt(_ZN4gem510BaseKvmCPU4tickEv+0x99)[0x55e6b2f50b39]
./build/X86/gem5.opt(_ZN4gem510EventQueue10serviceOneEv+0xc2)[0x55e6b2c0df32]
./build/X86/gem5.opt(_ZN4gem59doSimLoopEPNS_10EventQueueE+0x68)[0x55e6b2c385c8]
./build/X86/gem5.opt(_ZN4gem58simulateEm+0x27b)[0x55e6b2c38bbb]
./build/X86/gem5.opt(+0xdd6960)[0x55e6b2482960]
./build/X86/gem5.opt(+0xa097b4)[0x55e6b20b57b4]
/lib/x86_64-linux-gnu/libpython3.10.so.1.0(+0x128023)[0x7fc8b44b1023]
/lib/x86_64-linux-gnu/libpython3.10.so.1.0(_PyObject_Call+0x5c)[0x7fc8b446afec]
/lib/x86_64-linux-gnu/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x4b16)[0x7fc8b43ff776]
/lib/x86_64-linux-gnu/libpython3.10.so.1.0(+0x1c23af)[0x7fc8b454b3af]
/lib/x86_64-linux-gnu/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x9d68)[0x7fc8b44049c8]
/lib/x86_64-linux-gnu/libpython3.10.so.1.0(+0x1c23af)[0x7fc8b454b3af]
/lib/x86_64-linux-gnu/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x69de)[0x7fc8b440163e]
/lib/x86_64-linux-gnu/libpython3.10.so.1.0(+0x1c23af)[0x7fc8b454b3af]
/lib/x86_64-linux-gnu/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x9d68)[0x7fc8b44049c8]
/lib/x86_64-linux-gnu/libpython3.10.so.1.0(+0x1c23af)[0x7fc8b454b3af]
/lib/x86_64-linux-gnu/libpython3.10.so.1.0(PyEval_EvalCode+0xbe)[0x7fc8b45463de]
/lib/x86_64-linux-gnu/libpython3.10.so.1.0(+0x1bd96d)[0x7fc8b454696d]
/lib/x86_64-linux-gnu/libpython3.10.so.1.0(+0x1287b3)[0x7fc8b44b17b3]
--- END LIBC BACKTRACE ---
```

Actual stderr output of `memset` when run using X86KvmCPU:
```
memset failed at address 0x7ffff7ffe000: 00 != ab
```

**Expected behavior**
Both `./xmm` and `./memset` should print nothing and exit cleanly with exit code 0.

**Host Operating System**
Ubuntu 22.04

**Host ISA**
X86

**Compiler used**
GCC 11.0.4

**Additional information**
I'll be making a pull request to fix this bug soon

### PR DESCRIPTION
**Pull request by nmosier**
If the XSAVE KVM capability is available (KVM_CAP_XSAVE), the X86KvmCPU will try to set the x87 FPU + SSE state using KVM_SET_XSAVE, which expects a buffer (struct kvm_xsave) in XSAVE area format (Vol. 1, Sec. 13.4 of Intel x86 SDM). The original implementation of `X86KvmCPU::updateKvmStateFPUXSave()`, however, improperly sets the xsave header, which contains a bitmap of state components present in the xsave area.

This patch defines `XSaveHeader` structure to model the xsave header, which is expected directly following the legacy FPU region (defined in the `FXSave` structure) in the xsave area. It then sets two bist in the xsave header to indicate the presence of x86 FPU and SSE state components.

GitHub issue: https://github.com/gem5/gem5/issues/296

Change-Id: I5c5c7925fa7f78a7b5e2adc209187deff53ac039

### CODE REVIEW

**Review by abmerop — APPROVED** [review]
Good find!  I was able to reproduce the memset test and this indeed fixes it.  I use KVM almost exclusively and this doesn't seem to cause any other issues so far, so approving to start testing.

Seems there might be a similar problem with AVX, but I don't think gem5 turns on the AVX CPUID bit by default.

**Comment by nmosier** [comment]
Great! I noticed one test (BaseCPUProcessor-arm-hello-ALL-x86_64-opt) failed in the GitHub actions, but all tests pass (including that one) when I run the tests on my own computer (with `./main.py run` in the tests directory). Is that just a flaky test?

**Comment by abmerop** [comment]
I'm not sure about the tests.  Supposedly you can download the outputs from the github action here: https://github.com/gem5/gem5/actions/runs/6137973380?pr=298 . 

However for me this just contains a corrupted zip file inside the zip file, so I am not sure how to check. Perhaps @BobbyRBruce  or @powerjg can help.  If it's flaky I guess rerunning might work too.

**Comment by powerjg** [comment]
I can't imagine why your change would cause that test to fail... I just re-ran it. Let's see what happens this time.

It's odd, because these test shouldn't be flaky anymore...

**Pull request merged**
