### PR TITLE
scons: Use pkgconfig to get correct Protobuf dependency

### PR DESCRIPTION
**Pull request by wmin0**
Latest protobuf library depends on abseil libraries. We should rely on pkgconfig to give us correct dependency. We still keep the old check as fallback.

Change-Id: I529ea1f61e5bbc16b2520ab1badff3d8264f1c33

### CODE REVIEW

**Review by powerjg — APPROVED** [review]

**Comment by wmin0** [comment]
Hi Jason,

It seems the failed test are all related to RISCV. Do you know if there's WIP change to fix this?
```
Test: asm-riscv-rv64ui-ps-blt-atomic-ALL-x86_64-opt Failed
Test: asm-riscv-rv64ui-ps-bltu-atomic-ALL-x86_64-opt Failed
Test: asm-riscv-rv64ui-ps-bne-atomic-ALL-x86_64-opt Failed
Test: asm-riscv-rv64ui-ps-fence_i-atomic-ALL-x86_64-opt Failed
Test: asm-riscv-rv64ui-ps-jal-atomic-ALL-x86_64-opt Failed
Test: asm-riscv-rv64ui-ps-jalr-atomic-ALL-x86_64-opt Failed
Test: asm-riscv-rv64ui-ps-lb-atomic-ALL-x86_64-opt Failed
```

Thanks.

**Comment by wmin0** [comment]
@powerjg sorry I forgot to use @ to generate the notification.

**Comment by powerjg** [comment]
We're having problems with downloading some resources when running the CI tests. We're looking into it.

**Comment by wmin0** [comment]
@powerjg Thanks for help. It seems I need to wait for maintainers to merge my change to develop branch for now. I am figuring out the github flow :)

**Comment by powerjg** [comment]
We're all figuring it out :)

**Comment by wmin0** [comment]
@powerjg Would you like to help the change again? I'm not sure why it needs another approval...

**Comment by powerjg** [comment]
Sorry about that. Once this is committed, then it shouldn't ask again. We have it set up such that "first time contributors" need the approval to run the CI tests since the tests run on our local infrastructure.

**Comment by wmin0** [comment]
Thanks for your help. I'll bring the experience back to tell folks about how to work with the new flow.

**Pull request merged**
