### PR TITLE
arch-riscv: Add bootloader+kernel workload

### PR DESCRIPTION
**Pull request by hnpl**
Aims to boot OpenSBI + Linux kernel.

Change-Id: I9ee93cc367e8c06bdd0c7ddf43335d32965be14d

### CODE REVIEW

**Comment by hnpl** [comment]
This is a prototype of the bootloader + kernel workload. This is roughly a combination of the RISCV's FsLinux workload and RISCV's BareMetal workload.

I'll remove the "draft" status when I finished testing this.

**Comment by powerjg** [comment]
@Harshil2107 FYI, we're going to put testing and finishing upstreaming this on your plate. Let's try to get this done in the next week or so. You can work with Hoa to figure out the details.

**Comment by hnpl** [comment]
@Harshil2107 I'll put together some hack to test this so we can get this C++ backend of the workload object (https://github.com/gem5/gem5/pull/390) and the related resources (https://github.com/gem5/gem5-resources/pull/13) in. We can work on the python interface for these resources later.

**Comment by hnpl** [comment]
I've tested this setup with the bootloader and the linux kernel produced from https://github.com/gem5/gem5-resources/pull/13. I haven't tested booting Ubuntu yet, but gem5 was able to boot the linux kernel.

@Harshil2107 You can test this change by applying this patch on top of this change, https://github.com/hnpl/gem5/commit/1cdec307c835ff1b7b19cb85a859dbc7df308082.patch.

You can run the test script using,

```sh
build/RISCV/gem5.opt riscv-fs-test.py \
    --command="m5 exit"\
    --bootloader=<path/to/fw_jump.elf>\
    --kernel=<path/to/vmlinux>\
    --disk-image=<path/to/disk-image>
```

The bootloader and the linux kernel should be produced by following https://github.com/gem5/gem5-resources/pull/13.
I don't know if we have other RISC-V disk image around, but I have one at `/projects/gem5/hn/DISK_IMAGES/rv64gc-hpc-2204.img`.

**Comment by Harshil2107** [comment]
I will look into it today.

**Comment by Harshil2107** [comment]
Looks good to me.

**Review by Harshil2107 — APPROVED** [review]

**Comment by BobbyRBruce** [comment]
> Looks good to me.

This means you ran the test and it works as intended? Just want to verify before merging.

**Comment by Harshil2107** [comment]
Yes

**Pull request merged**
