### PR TITLE
tests,arch-riscv: update bitmanip asmtest binaries

### PR DESCRIPTION
**Pull request by rogerchang23424**
Gem5 resource update: https://github.com/gem5/gem5-resources/pull/25
Gem5 issue: https://github.com/gem5/gem5/issues/883

Change-Id: I1892d7591d6fa49d0563623fd90292e0d38d9ba3

### CODE REVIEW

**Comment by powerjg** [comment]
I assume this requires updating the binaries that are downloaded from the gem5-resources store based on https://github.com/gem5/gem5-resources/pull/25

cc: @Harshil2107

**Comment by rogerchang23424** [comment]
Wait for resource updated to review the PR

**Comment by Harshil2107** [comment]
I noticed that the asmtest is failing, I see some names of the tests have been changed, should these have been completely new resources? 

I thought we just need to update the existing binaries so I jsut updated the version and did not  add the binaries as a new resource.

**Comment by rogerchang23424** [comment]
Hi @Harshil2107 

> I noticed that the asmtest is failing, I see some names of the tests have been changed, should these have been completely new resources?

No, There are existing in the gem5 resource. All of bitmanip files (`rv64ub*` and `rv32ub*`) are renamed. For example, `rv64ub-ps-add_uw` changes to `rv64uzba-ps-add_uw`, `rv32ub-ps-ror` changes to `rv32uzbb-ps-ror`. It's requested from upstream (https://github.com/riscv-software-src/riscv-tests/pull/539#pullrequestreview-1887064313).

For me, it OK for me to use either the original filename or the upstream filename. If we want to keep the original filename for bitmanip test cases, I can close the PR.

Thanks

**Comment by Harshil2107** [comment]
I just wanted to confirm, I can add them as new resources, I just wanted to clarify. Just to confirm, we need all the 32 bit binaries remade and only the updated ones on 64 bit?

**Comment by rogerchang23424** [comment]
Please remade all of the 32 bits binaries and update the 64bits test binary names, thanks.

**Comment by Harshil2107** [comment]
I have updated the names and re ran the tests. The tests should pass now.

**Review by BobbyRBruce — APPROVED** [review]

**Review by Harshil2107 — APPROVED** [review]

**Pull request merged**
