### PR TITLE
arch-x86: Fix two_byte_opcodes.isa `0x6` -> `0x0`

### LINKED ISSUE #664: X86 Simulation failing to exit simulation loop due to invalid opcode
**Describe the bug**

X86 Simulations are failing to exit the simulation loop with an `invalid opcode: 0000 [#4] SMP NOPTI` error. This is causing our [Daily Tests](https://github.com/gem5/gem5/actions/runs/7029236400) and [Weekly Tests](https://github.com/gem5/gem5/actions/runs/7041468549) to fail with timeouts for X86 Boot tests.

This bug was introduced by #593 and can be fixed ~~via a reversion: #663~~ with #666

**Affects version**

Currently affects the `develop` branch as well as the `release-staging-v23-1` branch. This bug appears to have been introduced by #593 (Commit: 3fe5e58f2832cc9b8712058db96373a57d36c462).

**To Reproduce**

```shell
scons build/ALL/gem5.opt -j12
./build/ALL/gem5.opt configs/example/gem5_library/x86-ubuntu-run.py
# Alternatively, for KVM compatible machines:
# ./build/ALL/gem5.opt configs/example/gem5_library/x86-ubuntu-run-with-kvm.py
```

The Ubuntu boot will complete but will fail when attempting to exit the simulation loop, thus leaving the simulation in the loop indefinitely.

**Output**

[terminal-output.txt](https://github.com/gem5/gem5/files/13606393/terminal-output.txt)

```shell
CPU: 0 PID: 1151 Comm: gem5_init.sh Not tainted 5.4.49 #8
StaHardware name:  , BIOS  06/08/2008
rting gRIP: 0010:__show_regs+0x136/0x236
em5 iniCtode: fc ff ff bf 01 01 00 c0 48 89 44 24 10 e8 c0 fc ff ff bf 02 01 00 c0 48 89 44 24 08 41 8c dd e8 ae fc ff ff 41 8c c6 49 89 c1 <41> 0f 20 c7 0f 20 d3 0f 20 d8 48 89 04 24 41 0f 20 e4 44 8b 44 24
... RrSP: 0000:ffffc90000107b98 EFLAGS: 0000006e
eadiRAX: 0000000000000000 RBX: 0000000000000001 RCX: 00000000c0000102
ng rRDX: 00000000c0000101 RSI: ffffc90000107a7c RDI: 00000000c0000102
un scRBP: ffffc90000107cc8 R08: 0000000000000000 R09: 0000000000000000
riptR10: 0000000200000000 R11: 0000000000000064 R12: 0000000000000000
 filR13: 0000000000000000 R14: 0000000000000000 R15: ffff8880bcbee500
e.
Rinvalid opcode: 0000 [#4] SMP NOPTI
```
**Host Operating System**

Ubuntu 22.04

**Host ISA**

X86 (with KVM enabled)

**Compiler used**

GCC 11.4.0

### PR DESCRIPTION
**Pull request by BobbyRBruce**
This bug was introduced by https://github.com/gem5/gem5/pull/593 and caused Issue https://github.com/gem5/gem5/issues/664.

Change-Id: Ia55de364ee8260e1fe315e37e1cffbc71ab229fb

### CODE REVIEW

**Comment by BobbyRBruce** [comment]
@OdnetninI

**Review by powerjg — APPROVED** [review]

**Review by hnpl — APPROVED** [review]
LGTM. More context, https://github.com/gem5/gem5/commit/670bf6a488a12a61840655644d4c0baf4377ecf3#diff-0a82410c39d1eb22c5ad03fa79c8a10122c91271061b498a26eded748f93513eL293.

**Comment by OdnetninI** [comment]
@BobbyRBruce I am so sorry about the bug.

I am checking, and I think I introduced the bug when moving the patch from my development into my gem5 fork.

Please, merge it to fix the issue.

**Comment by powerjg** [comment]
@BobbyRBruce I merged this, but it needs to be cherry-picked onto staging

**Pull request merged**
