### PR TITLE
Learning-gem5: fix formatting

### PR DESCRIPTION
**Pull request by ivanaamit**
Using f-strings instead of % for formatting.

### CODE REVIEW

**Comment by BobbyRBruce** [comment]
It seems you have a small rebase issues (note the additional commit you're accidently incorporating here). The fix is actually quite simple. Do the following in your repository:

```sh
# Add the gem5 repo as a remote repo (you may have
# already done this)
git remote add upstream git@github.com:gem5/gem5.git

# Obtain the upstream (gem5 mainline) develop branch.
# Let's call it 'upstream-develop'.
git switch -c upstream-develop --track upstream/develop

# Got back to your the branch
git switch learning-gem5-fix-formatting

# New rebase your branch on top of upstream-develop
git rebase upstream-develop

# Now we've cleaned everything up! All you need to do is 'force push'.

git push --force
```

Once you do that this PR should be looking a lot better.

**Review by powerjg — COMMENTED** [review]
This looks good to me. Did you happen to check the other files in this directory to see if they have any of the old style formatting?

**Comment by BobbyRBruce** [comment]
I've been playing around a bit with our pre-commit hooks (just to see if there's anything we can do). `[pyupgrade](https://github.com/asottile/pyupgrade)` converts strings into fstrings as part of it's syntax upgrading process, This commit: https://github.com/gem5/gem5/pull/406/commits/2b73b67d2f04a45e22d236ac146d957e022e3b5c shows what it does.

Just thought i'd mention it :).

**Comment by ivanaamit** [comment]
I have updated a few more files in configs/learning-gem5.

In the future, I would like to use what Bobby suggested.

**Review by powerjg — APPROVED** [review]

**Review by powerjg — CHANGES_REQUESTED** [review]
Some commits don't conform to the commit guidelines. I would squash into a single commit.

**Comment by powerjg** [comment]
Can you update this with the current develop and rebase instead of merge so that you have just one commit?

**Comment by BobbyRBruce** [comment]
Hey @ivanaamit : I totally overthought this during this morning's meeting. A simple(-ish) rebase should work. Try the following:

```sh
# Ensure you have the main gem5/gem5 repo setup as "upstream"
git remote add upstream https://github.com/gem5/gem5.git

# Get the lastest from upstream
git fetch upstream

# Ensure we are on this branch
git switch learning-gem5-fix-format

# Rebase on top of gem5/gem5's develop branch
git rebase upstream/develop
```

When done you can see `git log` and see this is now just one commit.

Then `git push --force` should push the changes.

**Review by powerjg — APPROVED** [review]

**Pull request merged**
