### PR TITLE
arch-riscv: Update riscv matched board

### LINKED ISSUE #616: Update RISCV kernel and refactor stdlib to use the new kernel and bootloader workload.
A new RISCV kernel and bootloader was introduced with the patcher #390 and gem5-resources 13 (https://github.com/gem5/gem5-resources/pull/13). We can refactor stdlib to use these new resources.

These are the to-dos to implement this change:

- [x] Mark the old kernel as deprecated, In our case we can just edit the `gem5-versions` field in the JSON of the resource to do this.
- [x] build and add the resources mentioned in gem5-resources 13.
- [x] Refactor the stdlib to use the RiscvISA::BootloaderKernelWorkload rather than RiscvISA::FsWorkload
- [x] Update the tests in tests/ to use the newer kernel/bootloader.

### PR DESCRIPTION
**Pull request by Harshil2107**
- Update riscv matched board to work with new RiscvBootloaderKernelWorkload

Change-Id: Ic20b964f33e73b76775bfe18798bd667f36253f6

### CODE REVIEW

**Review by hnpl — APPROVED** [review]

**Review by powerjg — DISMISSED** [review]

**Review by rogerchang23424 — COMMENTED** [review]
To change the workload to bootloader+kernel, the chosen node need to add to device tree to avoid hanging.

RiscvBoard: https://github.com/gem5/gem5/pull/390

**Review by hnpl — COMMENTED** [review]
Thanks @rogerchang23424.

@Harshil2107, as Roger pointed out, we'll need to add the chosen node to the device tree like it's done here https://github.com/gem5/gem5/blob/7b986419533083dc48d961dcc502701f673a9af2/src/python/gem5/components/boards/riscv_board.py#L258-L261.

It should be added around line 350 of riscvmatched_board.py file.

**Comment by Harshil2107** [comment]
I made the required changes and The riscvmatched-fs.py script did end with the new kernel bootloader workload, I am attaching the workload file here and the command that I use to run this workload.

[example-workload.json](https://github.com/gem5/gem5/files/13594934/example-workload.1.json)

The command to run:
```
GEM5_RESOURCE_JSON_APPEND=path/to/example-workload.json ./build/RISCV/gem5.opt configs/example/gem5_library/riscvmatched-fs.py 
```

**Review by hnpl — APPROVED** [review]
lgtm

**Review by rogerchang23424 — APPROVED** [review]

**Review by powerjg — APPROVED** [review]

**Pull request merged**
