### PR TITLE
python,util: Fix magic number check in decode_inst_dep_trace.py

### LINKED ISSUE #543: unable to decode instruction dependency trace
**Describe the bug**
`decode_inst_dep_trace.py` script fails to decode trace.

**Affects version**
Current develop branch

**gem5 Modifications**
Unmodified

**To Reproduce**
Steps to reproduce the behavior. Please assume starting from a clean repository:

1. Compile gem5:
`$ python3 '`'which scons'`' build/X86/gem5.opt -j7`

2. Execute the simulation to get the traces:

As per the documentation for TraceCPU,
`$ ./build/RISCV/gem5.fast -d hello_world_RISCV configs/deprecated/example/se.py --cpu-type=RiscvO3CPU --caches --cmd=tests/test-progs/hello/bin/riscv/linux/hello --elastic-trace-en --data-trace-file=datatrc.helloworld.riscv.gz --inst-trace-file=insttrace.helloworld.riscv.gz --mem-type=SimpleMemory
`The trace completes fine.

A snippet from the output:

```
**** REAL SIMULATION ****
src/sim/simulate.cc:194: info: Entering event queue @ 0.  Starting simulation...
src/sim/mem_state.cc:443: info: Increasing stack size by one page.
Hello world!
Exiting @ tick 5476500 because exiting with last active thread context

```
3. Decode the traces
```
$ ./build/RISCV/gem5.fast util/decode_inst_dep_trace.py hello_world_RISCV/system.cpu.traceListener.datatrc.helloworld.riscv hello_world_RISCV/system.cpu.traceListener.datatrc.helloworld.riscv.out
gem5 Simulator System.  https://www.gem5.org
gem5 is copyrighted software; use the --copyright option for details.

gem5 version 23.0.1.0
gem5 compiled Nov  5 2023 12:15:24
gem5 started Nov  5 2023 21:05:46
gem5 executing on lab315, pid 131797
command line: ./build/RISCV/gem5.fast util/decode_inst_dep_trace.py hello_world_RISCV/system.cpu.traceListener.datatrc.helloworld.riscv hello_world_RISCV/system.cpu.traceListener.datatrc.helloworld.riscv.out

Did not find proto definition, attempting to generate
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

At:
  /usr/local/lib/python3.8/dist-packages/google/protobuf/descriptor.py(780): __new__
  /home/rajarshi/temp/gem5/util/inst_dep_record_pb2.py(33): <module>
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(848): exec_module
  <frozen importlib._bootstrap>(686): _load_unlocked
  <frozen importlib._bootstrap>(975): _find_and_load_unlocked
  <frozen importlib._bootstrap>(991): _find_and_load
  util/decode_inst_dep_trace.py(110): <module>
  src/python/m5/main.py(630): main


```
4. Installed proto compiler v25 from https://github.com/protocolbuffers/protobuf/releases/download/v25.0/protoc-25.0-linux-x86_64.zip
The above issue is now addressed,

```
$ ./build/RISCV/gem5.fast util/decode_inst_dep_trace.py hello_world_RISCV/system.cpu.traceListener.datatrc.helloworld.riscv hello_world_RISCV/system.cpu.traceListener.datatrc.helloworld.riscv.out
gem5 Simulator System.  https://www.gem5.org
gem5 is copyrighted software; use the --copyright option for details.

gem5 version 23.0.1.0
gem5 compiled Nov  5 2023 12:15:24
gem5 started Nov  6 2023 15:18:48
gem5 executing on lab315, pid 134309
command line: ./build/RISCV/gem5.fast util/decode_inst_dep_trace.py hello_world_RISCV/system.cpu.traceListener.datatrc.helloworld.riscv hello_world_RISCV/system.cpu.traceListener.datatrc.helloworld.riscv.out

Did not find proto definition, attempting to generate
Generated proto definitions for instruction dependency record


```
However, the trace decode output is not generated.

5. Then I used the python script directly.

```
$ python3 util/decode_inst_dep_trace.py hello_world_RISCV/system.cpu.traceListener.datatrc.helloworld.riscv.gz hello_world_RISCV/system.cpu.traceListener.datatrc.helloworld.riscv.out
debug. imported inst_dep_record_pb2
debug. in __main__
debug. in main() sys.argv: ['util/decode_inst_dep_trace.py', 'hello_world_RISCV/system.cpu.traceListener.datatrc.helloworld.riscv.gz', 'hello_world_RISCV/system.cpu.traceListener.datatrc.helloworld.riscv.out']
debug. in main() completed calling protolib.openFileRd()
Unrecognized file

```
But the trace decode fails with the error '`Unrecognized file`'.

**Terminal Output**
```shell
#Terminal output here#
$ python3 util/decode_inst_dep_trace.py hello_world_RISCV/system.cpu.traceListener.datatrc.helloworld.riscv.gz hello_world_RISCV/system.cpu.traceListener.datatrc.helloworld.riscv.out
debug. imported inst_dep_record_pb2
debug. in __main__
debug. in main() sys.argv: ['util/decode_inst_dep_trace.py', 'hello_world_RISCV/system.cpu.traceListener.datatrc.helloworld.riscv.gz', 'hello_world_RISCV/system.cpu.traceListener.datatrc.helloworld.riscv.out']
debug. in main() completed calling protolib.openFileRd()
Unrecognized file
```

**Expected behavior**
The script is expected to run successfully and generate the decoded trace output.

**Host Operating System**
Ubuntu 20.04

**Host ISA**
X86

**Compiler used**
```
$ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0


```
**Additional information**
This behaviour is not seen with the decode_packet_trace.py script which works fine.

### PR DESCRIPTION
**Pull request by drajarshi**
The decode_inst_dep_trace.py opens the trace file in read mode, and subsequently reads the magic number from the trace file. Once the number is read, it is compared against the string 'gem5' without decoding it first. This causes the comparison to fail.
The fix addresses this by calling the decode() routine on the output of the read() call. Please find the details in the associated issue #543

### CODE REVIEW

**Comment by Harshil2107** [comment]
Hi @drajarshi ,

All pull requests to gem5 require Change IDs to be present in all commit messages. The commits in this PR do not have Change IDs. Please follow these steps to add a change ID to your commits:

1. Run the following commands:
```
f=.git/hooks/commit-msg
mkdir -p 
curl -Lo $f https://gerrit-review.googlesource.com/tools/hooks/commit-msg
chmod +x $f/commit-msg
```

2. Then, amend the commit with `git commit --amend --no-edit`, and update your pull request.

**Review by powerjg — APPROVED** [review]
Lgtm. Thanks for the contribution!

**Comment by drajarshi** [comment]
Thanks @powerjg @Harshil2107

**Comment by drajarshi** [comment]
Thanks @BobbyRBruce

**Pull request merged**
