### PR TITLE
arch-riscv: Improved vector instructions

### LINKED ISSUE #1645: riscv simulation raises panic condition
**Describe the bug**
running vlseg4e32 instruction causes panic condition

**Affects version**
commit b1a44b89c

**gem5 Modifications**

building the vec-fft benchmark from https://github.com/ucb-bar/saturn-vectors/tree/master/benchmarks/vec-fft

1. Compile gem5 with command ...  scons build/RISCV/gem5.opt
2. Execute the simulation with...
riscv64-unknown-elf-gcc -DPREALLOCATE=1 -march=rv64imafdcv -mabi=lp64d -O3 -ftree-vectorize  -ffast-math -fno-common fft2_main.c vec-fft2.c  -o FFT

build/RISCV/gem5.opt ../Test/riscv.py

```python
import m5
from m5.objects import *


class L1Cache(Cache):
    assoc = 2
    tag_latency = 1
    data_latency = 1
    response_latency = 1
    mshrs = 4
    tgts_per_mshr = 20

    def connectCPU(self, cpu):
        raise NotImplementedError

    def connectBus(self, bus):
        self.mem_side = bus.cpu_side_ports


class L1ICache(L1Cache):
    size = '512kB'

    def connectCPU(self, cpu):
        self.cpu_side = cpu.icache_port


class L1DCache(L1Cache):
    size = '1024kB'

    def connectCPU(self, cpu):
        self.cpu_side = cpu.dcache_port


class L2Cache(Cache):
    size = '1024kB'
    assoc = 8
    tag_latency = 1
    data_latency = 1
    response_latency = 1
    mshrs = 20
    tgts_per_mshr = 12

    def connectCPUSideBus(self, bus):
        self.cpu_side = bus.mem_side_ports

    def connectMemSideBus(self, bus):
        self.mem_side = bus.cpu_side_ports


system = System()

system.clk_domain = SrcClockDomain()
system.clk_domain.clock = "800MHz"
system.clk_domain.voltage_domain = VoltageDomain()

system.mem_mode = "timing"
system.mem_ranges = [AddrRange("1024MB")]
system.cpu = RiscvO3CPU()
#system.cpu = RiscvMinorCPU()
system.cpu.isa = RiscvISA(vlen=256, elen=32)

# Create the L1 caches
system.cpu.icache = L1ICache()
system.cpu.dcache = L1DCache()

# Connect the caches to the CPU
system.cpu.icache.connectCPU(system.cpu)
system.cpu.dcache.connectCPU(system.cpu)

# Connect the CPU to the L2 bus
system.l2bus = L2XBar()

# Connect the L1 caches to the L2 bus
system.cpu.icache.connectBus(system.l2bus)
system.cpu.dcache.connectBus(system.l2bus)

# Connect the L2 cache to the CPU side bus
system.l2cache = L2Cache()
system.l2cache.connectCPUSideBus(system.l2bus)

# Connect the L2 cache to the memory bus
system.membus = SystemXBar()
system.l2cache.connectMemSideBus(system.membus)

# Connect the CPU to the memory bus
system.cpu.createInterruptController()


system.mem_ctrl = MemCtrl()
system.mem_ctrl.dram = DDR3_1600_8x8()
system.mem_ctrl.dram.range = system.mem_ranges[0]
system.mem_ctrl.port = system.membus.mem_side_ports

system.system_port = system.membus.cpu_side_ports

thispath = os.path.dirname(os.path.realpath(__file__))
binary = '/vec-fft/FFT'

system.workload = SEWorkload.init_compatible(binary)

process = Process()
process.cmd = [binary]
system.cpu.workload = process
system.cpu.createThreads()
root = Root(full_system=False, system=system)
m5.instantiate()

print(f"Beginning simulation!")
exit_event = m5.simulate()
  

print(f"Exiting @ tick {m5.curTick()} because {exit_event.getCause()}")
```

**Terminal Output**
Beginning simulation!
src/sim/simulate.cc:199: info: Entering event queue @ 0.  Starting simulation...
build/RISCV/arch/riscv/generated/exec-ns.cc.inc:10499: panic: panic condition (pow(2, vlmul) * this->numFields) > 8 occurred: LMUL value is illegal for vlseg inst

**Expected behavior**
Spike simulation goes through without any issues. 

**Host Operating System**
Ubuntu 22.04 on WSL.

**Host ISA**
RISC-V

### LINKED ISSUE #1667: Incorrect riscv vslide instruction implementation
**Describe the bug**
The execution result of the riscv vector slide instruction is not as expected. The picture of trace here shows the bug. (vlen=128)

The results in trace do not conform to the description in the [specification](https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#vector-slide-instructions).

截屏2024-10-12 下午4 50 01

The correct result of vslideup(0x106b4) shoule be:
```
vslideup_vi_micro v0 : SimdMisc :  D=[00000000_00000000_00000000_00000000]
vslideup_vi_micro v1 : SimdMisc :  D=[00010101_01010101_01010101_01010101]
vslideup_vi_micro v2 : SimdMisc :  D=[01020202_02020202_02020202_02020202]
vslideup_vi_micro v3 : SimdMisc :  D=[02030303_03030303_03030303_03030303]
```

 The correct result of vslidedown(0x106dc) shoule be:
```
vslidedown_vi_micro v0 : SimdMisc :  D=[02020202_02020202_02020202_02020203]
vslidedown_vi_micro v1 : SimdMisc :  D=[03030303_03030303_03030303_03030304]
vslidedown_vi_micro v2 : SimdMisc :  D=[04040404_04040404_04040404_04040400]
vslidedown_vi_micro v3 : SimdMisc :  D=[00000000_00000000_00000000_00000000]
```

In addition, the slide instruction whose offset is an immediate value can statically filter out redundant uops during decoding to improve performance.  For example, lines 3551, 3552, 3554, 3555, 3556, and 3558 in the picture above.

**Affects version**
Develop branch. Commit [a8f88abfb12f772f496aad2b9866476f7ebb575c](https://github.com/gem5/gem5/tree/a8f88abfb12f772f496aad2b9866476f7ebb575c).

**gem5 Modifications**
#1712

**To Reproduce**
[Here](https://github.com/user-attachments/files/17349445/slide.tar.gz) is a simple test. Use the `slide` elf file and `se.py` script in `gz` package file to simulate. And dump the Exec trace.

**Terminal Output**
```shell
gem5 Simulator System.  https://www.gem5.org
gem5 is copyrighted software; use the --copyright option for details.

gem5 version DEVELOP-FOR-24.1
gem5 compiled Oct 12 2024 16:38:05
gem5 started Oct 12 2024 16:42:42
gem5 executing on n37-094-005, pid 126645
command line: ./build/RISCV/gem5.opt --debug-flags=Exec --debug-start=70593000 --debug-file=trace.out configs/bytedance/orca/se.py --cmd /data00/home/hongzhibo/share/benchmark/slide/slide

warn: Base 10 memory/cache size 1kB will be cast to base 2 size 1KiB.
warn: Base 10 memory/cache size 1kB will be cast to base 2 size 1KiB.
warn: The se.py script is deprecated. It will be removed in future releases of  gem5.
warn: Base 10 memory/cache size 8GB will be cast to base 2 size 8GiB.
warn: Base 10 memory/cache size 1MB will be cast to base 2 size 1MiB.
warn: Base 10 memory/cache size 64MB will be cast to base 2 size 64MiB.
warn: Base 10 memory/cache size 64kB will be cast to base 2 size 64KiB.
warn: Base 10 memory/cache size 64kB will be cast to base 2 size 64KiB.
warn: Base 10 memory/cache size 1MB will be cast to base 2 size 1MiB.
Global frequency set at 1000000000000 ticks per second
warn: system.cpu.dcache.prefetcher adopting orphan SimObject param 'prefetchers'
src/arch/riscv/isa.cc:278: info: RVV enabled, VLEN = 128 bits, ELEN = 64 bits
src/base/statistics.hh:279: warn: One of the stats is a legacy stat. Legacy stat is a stat that does not belong to any statistics::Group. Legacy stat is deprecated.
system.remote_gdb: Listening for connections on port 7000
**** REAL SIMULATION ****
src/sim/simulate.cc:199: info: Entering event queue @ 0.  Starting simulation...
src/sim/syscall_emul.cc:97: warn: ignoring syscall set_robust_list(...)
      (further warnings will be suppressed)
src/sim/mem_state.cc:448: info: Increasing stack size by one page.
src/sim/syscall_emul.cc:86: warn: ignoring syscall mprotect(...)
Exiting @ tick 78593000 because exiting with last active thread context
```

**Expected behavior**
You can see the above picture from the trace file. The results of the vslideup and vslidedown instructions do not meet the riscv vector specifications.

**Host Operating System**
Debian 12.

**Host ISA**
X86

**Compiler used**
gcc 14

### LINKED ISSUE #1668: Incorrect riscv vector unit-stride segment load/store instructions
**Describe the bug**
The execution result of the riscv vector unit-stride segment load/store instruction is not as expected. The picture of trace here shows the bug. (vlen=128).

The results in trace do not conform to the description in the [specification](https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#sec-aos).

截屏2024-10-12 下午7 30 36

The correct result of vlseg2e8.v(0x106b4) shoule be:
```
vlseg2e8_v_micro v0, (a0), zero : SimdUnitStrideSegmentedLoad :  D=[00020406_080a0c0e_10121416_181a1c1e]
vlseg2e8_v_micro v1, (a0), zero : SimdUnitStrideSegmentedLoad :  D=[01030507_090b0d0f_11131517_191b1d1f]
```

**Affects version**
Develop branch. Commit [a8f88abfb12f772f496aad2b9866476f7ebb575c](https://github.com/gem5/gem5/tree/a8f88abfb12f772f496aad2b9866476f7ebb575c).

**gem5 Modifications**
#1669

**To Reproduce**
[Here](https://github.com/user-attachments/files/17349831/vlseg.tar.gz) is a simple test. Use the `vlseg` elf file and `se.py` script in `gz` package file to simulate. And dump the Exec trace.

**Terminal Output**
If applicable, add the terminal output here. If long, only include the relevant lines.
Please put the terminal output in code blocks. I.e.:

```shell
/data00/home/hongzhibo/share/benchmark/vlseg/vlseg
gem5 Simulator System.  https://www.gem5.org
gem5 is copyrighted software; use the --copyright option for details.

gem5 version DEVELOP-FOR-24.1
gem5 compiled Oct 12 2024 14:28:11
gem5 started Oct 12 2024 18:34:40
gem5 executing on n37-094-005, pid 385420
command line: ./build/RISCV/gem5.opt --debug-flags=Exec --debug-start=45690500 --debug-file=trace.out configs/deprecated/example/se.py --cmd /data00/home/hongzhibo/share/benchmark/vlseg/vlseg

warn: The se.py script is deprecated. It will be removed in future releases of  gem5.
Global frequency set at 1000000000000 ticks per second
src/mem/dram_interface.cc:690: warn: DRAM device capacity (8192 Mbytes) does not match the address range assigned (512 Mbytes)
src/arch/riscv/isa.cc:278: info: RVV enabled, VLEN = 128 bits, ELEN = 64 bits
src/base/statistics.hh:279: warn: One of the stats is a legacy stat. Legacy stat is a stat that does not belong to any statistics::Group. Legacy stat is deprecated.
system.remote_gdb: Listening for connections on port 7000
**** REAL SIMULATION ****
src/sim/simulate.cc:199: info: Entering event queue @ 0.  Starting simulation...
src/sim/syscall_emul.cc:97: warn: ignoring syscall set_robust_list(...)
      (further warnings will be suppressed)
src/sim/mem_state.cc:448: info: Increasing stack size by one page.
src/sim/syscall_emul.cc:86: warn: ignoring syscall mprotect(...)
Exiting @ tick 52690500 because exiting with last active thread context
```

**Expected behavior**
You can see the above picture from the trace file. The results of the vlseg2e8.v instruction do not meet the riscv vector specifications.

**Host Operating System**
Debian 12.

**Host ISA**
X86

**Compiler used**
gcc 14

### PR DESCRIPTION
**Pull request by 5265325**
This patch implements the missing riscv vector instructions and fixes some vector instruction bugs:

1. Add support for vector strided segment load/store instructions.
2. Add support for vector indexed segment load/store instructions.
3. Add support for fault-only-first unit-stride segment load instructions.
4. Static filtering uop for vslideup.vi/vslidedown.vi/vslide1up.vx /vsilde1down.vx/vfslide1up.vf/vfslide1down.vf instructions to improve performance. #1667
5. Fix widening instruction assertion caused by speculative execution. #1645
6. Fix incorrect vector unit-stride segment load/store instructions. #1668
7. Fix incorrect vector slide instructions. #1667

This PR have been tested using [this](https://github.com/5265325/rvv-intrinsic-doc/tree/gem5/examples) mentioned in #1542.

Change-Id: Ic03dcaa06701f5124e2c942532382bf68434a9fe

### CODE REVIEW

**Comment by powerjg** [comment]
Thanks for your contribution!

It is going to be difficult to review 3000 lines of code changed in a single commit. If you could break this up into multiple commits which address one issue at a time, it may take the community less time to review your change.

**Comment by 5265325** [comment]
> Thanks for your contribution!
> 
> It is going to be difficult to review 3000 lines of code changed in a single commit. If you could break this up into multiple commits which address one issue at a time, it may take the community less time to review your change.

Got it. I will try to separate it. Also, could you please review #1526.

**Comment by giactra** [comment]
This PR should also bear the cpu-o3 tag as it touches generic parts of the CPU model as well

**Comment by erin-le** [comment]
@5265325 Hello, I've noticed that you pushed PRs 1709 through 1712 recently, and that they mention some of the same issues as this PR. Does the newer set of PRs contain the same changes as this PR, and if so, can this PR be closed? Thank you!

**Comment by 5265325** [comment]
> @5265325 Hello, I've noticed that you pushed PRs 1709 through 1712 recently, and that they mention some of the same issues as this PR. Does the newer set of PRs contain the same changes as this PR, and if so, can this PR be closed? Thank you!

Yes, I separate this PR into multiple PRs. This PR will be closed.

**Pull request closed without merging**
